"""add department

Revision ID: 717214b2433a
Revises: c988afe9f893
Create Date: 2025-01-06 10:46:40.638818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717214b2433a'
down_revision = 'c988afe9f893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
