"""rename address

Revision ID: d92deb62196f
Revises: 5cabf9583e26
Create Date: 2025-01-06 10:52:36.604376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92deb62196f'
down_revision = '5cabf9583e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address',new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location',new_column_name='address')
    # ### end Alembic commands ###
